root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Just use main.go for binary name
  bin = "./tmp/main"
  # Adjust build command to target your main.go location
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  # Watch these file extensions
  include_ext = ["go", "yaml", "toml"]
  # Ignore these directories
  exclude_dir = [
    "assets",
    "tmp",
    "vendor",
    "testdata",
    "pkg/migration",
    "pkg/seeder",
    "docs"
  ]
  # Ignore test files
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  # Kill process before starting new one
  delay = 1000
  stop_on_error = true
  # Send interrupt signal before killing process
  send_interrupt = true
  # Kill process if it doesn't exit after interrupt signal
  kill_delay = "0.5s"

  # Build log path
  log = "build-errors.log"
  
  # Optional: Commands to run before build
  pre_cmd = []
  # Optional: Commands to run after build
  post_cmd = []
  
  # Reduce CPU usage
  poll = false
  poll_interval = 0

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  # Show build time
  time = true
  # Show main log only
  main_only = false

[misc]
  # Clean temporary directory on exit
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true